# Generated by Django 2.0 on 2018-04-09 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconstructor', '0002_image_file_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
